"""The full command list, grouped for /commands.

/start used to print all of these in one wall of text. New players bounced
off it, so /start now shows a short card and this catalogue lives behind
/commands (a collapsible rich message, one section per category).
"""

COMMAND_CATEGORIES = (
    ('🚀 Getting started', (
        '/debut /d - Create account & get your starter XI',
        '/claim /c - Claim 1 player + coins (hourly)',
        '/daily /dl - Daily reward (24h)',
        '/gspin /gs - Lucky Card Pick (8h)',
        '/purse /p - Check balance',
        '/botstatus - Bot ping, uptime & status',
        '/myprofile /me - Your profile',
        '/leaderboard /lb /top - Leaderboard',
    )),
    ('👥 Squad & players', (
        '/myroster /mr - View your roster',
        '/playingxi /pxi /xi - Playing XI',
        '/ximage /xiimg - Playing XI as an image',
        '/playerinfo /pi [name] - Player details',
        '/stats /st [name] - Player game stats',
        '/gstats [name] - Global stats — every owner, every match type',
        '/owners [name] - Who owns this player in this group',
        '/searchpl /sp [name] - Search player',
        '/searchovr /so [rating] - Search by OVR',
        '/buypl /buy /b [name] - Buy a player',
        '/swapplayers /swap [n1] [n2] - Swap positions',
        '/setcaptain /cap [name] - Set captain',
        '/teamname /tn [name] - Set team name',
        '/setteamlogo - Set your team crest (DM, needs admin approval)',
        "/setteamcolour [#hex] - Set your team's scorecard colour",
        '/release /rel [name|pos] - Release for coins',
        '/releasemultiple /relm [from] [to] - Range release',
        '/trade /tr @user - Trade players',
    )),
    ('🏏 Play matches', (
        '/catch [bet] [height] - Risk purse coins in the catching game',
        '/cm @user - Two-wicket challenge mode',
        '/cdraft - Challenge Draft: someone joins, then you both build an XI pick by pick from the full player pool (11 slots, two same-role cards a slot — you take one, your opponent gets the other), and play it out',
        '/letsplay /lp [overs] @user - Reply or tag to play with your own roster (20 overs, or 1-20: /lp 5 @user)',
        '/challengeIPL /cipl [overs] - Reply to a user to start an IPL challenge (20 overs, or 1-20: /cipl 6)',
        '/challengeBBL /cbbl - Reply to a user to start a BBL challenge',
        '/challengeINT /cint - Reply to a user to start an international challenge',
        '/unscramble - Create an Unscramble Player lobby',
        '/playmatch /pm @user - Play a match',
        '/wpm [overs] [@user] - Match lobby up to 20 overs; tag/reply to invite a player (Mini App)',
        '/vsbot [overs] - Play a bot opponent in chat',
        '/wpmbot [overs] - Play a bot opponent in the Mini App (up to 20 overs)',
        '/lpbot /lpb - Practice Lets Play vs the bot, your roster, 20 overs (unranked)',
        '/ciplbot /ciplb [league] - Practice a league match vs the bot (unranked)',
        '/endmatch /em - End match (fine applies)',
        '/clearmatches - Players in the match (or a bot admin) clear stuck matches here (no winner)',
        '/removematch @user - Admin: remove a player stuck in a match',
        '/resume /r - If buttons disappear mid-match',
        '/rcl - Resume a stuck Challenge League (/cipl) match',
    )),
    ('🏆 Ranked & records', (
        '/pitchstats /ps [pitch] - What each pitch actually does in Lets Play & League matches: runs/over, wickets/over, bat-first vs chasing win %, and which approaches earn',
        '/rank [@user] - Your ranked rating, division and ladder position 📈',
        "/ranked - This season's ranked ladder (paid by division at month end)",
        '/rivalry [@user] - Your rivalries, or the series with one player ⚔️',
        '/halloffame /hof - All-time records: top scores, best figures, streaks 🏛️',
    )),
    ('🗓 Tournaments & draft', (
        '/lptour @user - Play your Lets Play Tournament fixture (official result)',
        '/lpt - Lets Play Tournament hub: table, fixtures, teams',
        '/lptable /lptfixtures /lptteams /lptstats - Tournament table, schedule, field, leaders',
        "/pick <player> - Tournament Draft: make your pick when you're on the clock",
        '/dboard /dsquad /dqueue - Draft board, your squad, your auto-pick wishlist',
        '/dtrade /dtrades - Trade players with another franchise once the draft is done',
        '/ctour - Challenge League Tournament hub: table, fixtures, teams',
        '/cttable /ctfixtures /ctteams - Tournament table, schedule (done matches struck through), field',
        '/ctinjuries - Who is ruled out injured, and for how many more matches 🚑',
        "/clsd <team> - One team's schedule: standing, form, next matches, results",
        "/teamtourstats [team] - Your team's tournament by the numbers: standing, what you score and concede, best and worst totals, and your top run-scorers and wicket-takers",
        '/mvp - Tournament Most Valuable Player: batting + bowling + wins + POTM awards in one impact-point total',
        "/remindmatch [team] [vs team] - Admin: nudge two teams to play what they still owe — posts here and DMs both sides' owners and co-owners",
    )),
    ('🔨 Franchise Auction', (
        '/bid [amount] - Bid for the player on the block (bare /bid = the next minimum)',
        '/aboard - The live auction board',
        "/apurse [franchise] - Every purse, or one franchise's squad",
        '/artm yes|no - Answer a Right To Match on your former player',
        '/ainfo - Rules, sets, next player, squads, purses, sold & unsold — as buttons',
        '/arules - Purse, squad caps, base prices, bid steps, the clock — before you bid',
        '/asets /anextset /anextplayer - The sets, the next set, who is up next',
        '/asquad [team] /asoldlist /aunsoldlist - Squads, sold and unsold players',
        '/aretlock /apicks - Who kept whom, and the expansion picks',
    )),
    ('⚡ Traits', (
        '/traits /tt - Your traits & inventory',
        '/traitlist /tlist - Every trait, effect and price',
        "/traitboost - What your equipped traits add to your XI's Team Overall ⚡",
        '/traitshop /tshop - Daily trait shop',
        '/traitapply /tapply - Apply trait to player',
        '/traitupgrade /tup - Level up a trait',
        '/traitreplace /trep - Replace a trait',
        '/removetrait /rtrait - Remove a trait (back to inventory)',
        '/selltrait /tsell - Sell an inventory trait for gems',
        '/tradetrait /ttrade @user - Swap a trait, same level both ways',
    )),
)
